version: "2.1"
networks:
  network:
services:
  report_making_service:
    container_name: report_making_service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - network
  rabbitmq:
    container_name: rabbit_report_maker
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - network

